In [285]:
%load_ext autoreload
%autoreload 2

import os, sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [286]:
import simpy, numpy as np, pandas as pd
from typing import Literal
import seaborn as sns
import matplotlib.pyplot as plt

In [287]:
from src.simulations.farm import Farm
from models.cycle import Phase, Stock
from models.farm import FarmingModel

from src.simulations.fish import feeding_logs

In [288]:
env = simpy.Environment()
money = 1_000_000_00
num_fishes = 100
fish_size: Literal["Medium_Fingerlin"] = "Medium_Fingerlin"
duration = 90

In [289]:
print(feeding_logs)

[]

In [ ]:
farm_a_model = FarmingModel(
    stocks=[
        Stock(id=1, type="Catfish", phases=[Phase(duration, [1], 0, "Jumbo")], size=fish_size, count=num_fishes)
    ],
    feed_conversion_rate={0: 1.1}
)
farm_a = Farm(env, 'Random', money=money, ponds=[], feeds=[], farming_model=farm_a_model, seed=42)

In [ ]:
farm_b_model = FarmingModel(
    stocks=[
        Stock(id=1, type="Catfish", phases=[Phase(duration, [1], 0, "Jumbo")], size=fish_size, count=num_fishes)
    ],
    feed_conversion_rate={0: 1.2, 20: 1.5}
)
farm_b = Farm(env, 'Random', money=money, ponds=[], feeds=[], farming_model=farm_b_model, seed=42)

In [292]:
env.run(until=366)

In [293]:
print(feeding_logs)

[]

In [294]:
farm_a.money.level - money, farm_b.money.level - money

(43019332, 54522089)

In [295]:
farm_a.get_frame('fish_harvest')

    time     tag  total_weight  quantity     price  cycle_id
0   90.3  Farm_0         41697       100  10424345         0
1  180.3  Farm_0         31898       100   7974435         1
2  270.2  Farm_0         55871       100  13967850         2
3  360.2  Farm_0         54912       100  13727959         3

In [296]:
farm_b.get_frame('fish_harvest')

    time     tag  total_weight  quantity    price  cycle_id
0   90.3  Farm_0         19258        50  4814606         0
1  120.3  Farm_0         17945        50  4486327         1
2  150.3  Farm_0         17740        50  4435096         2
3  180.3  Farm_0         14154        50  3538408         3
4  210.2  Farm_0         28261        50  7065321         4
5  240.2  Farm_0         26880        50  6719981         5
6  270.2  Farm_0         27211        50  6802625         6
7  300.2  Farm_0         28021        50  7005335         7
8  330.2  Farm_0         28220        50  7055022         8
9  360.2  Farm_0         24377        50  6094352         9

In [297]:
a = {0: 1, 10: 3, 3: 5}
b = sorted(a.keys(), reverse=True)

print(b)

[10, 3, 0]